version: "3.2"
services:
  web:
    build:
      context: .
      dockerfile: ./php_apache/dockerfile
    volumes:
      - ./..:/var/www/html
    links:
      - mysql
    ports:
      - "8080:80"

  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ./..:/app
    command: bash -c "composer dump-autoload && composer install --ignore-platform-reqs"

  mysql:
    image: mysql:5.7
  #  volumes:
 #     - ./data/:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=memory
      - MYSQL_USER=memory
      - MYSQL_PASSWORD=memory